// <auto-generated />
using FateMakeupApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FateMakeupApi.Migrations
{
    [DbContext(typeof(MakeupDBContext))]
    [Migration("20250903061224_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FateMakeupApi.Makeup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Makeups");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Brand = "MAC",
                            Category = "Lips",
                            Description = "Long-lasting matte finish lipstick in Ruby Woo shade.",
                            Name = "Matte Lipstick",
                            Type = "Lipstick"
                        },
                        new
                        {
                            ID = 2,
                            Brand = "Maybelline",
                            Category = "Face",
                            Description = "Lightweight foundation with full coverage and SPF 20.",
                            Name = "Liquid Foundation",
                            Type = "Foundation"
                        },
                        new
                        {
                            ID = 3,
                            Brand = "Urban Decay",
                            Category = "Eyes",
                            Description = "12-shade palette featuring warm neutrals and shimmer tones.",
                            Name = "Eyeshadow Palette",
                            Type = "Eyeshadow"
                        },
                        new
                        {
                            ID = 4,
                            Brand = "L'Oréal",
                            Category = "Eyes",
                            Description = "Mascara that provides intense volume and length.",
                            Name = "Volumizing Mascara",
                            Type = "Mascara"
                        },
                        new
                        {
                            ID = 5,
                            Brand = "NARS",
                            Category = "Cheeks",
                            Description = "Highly pigmented blush in the shade Orgasm.",
                            Name = "Blush Powder",
                            Type = "Blush"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
